source 'http://rubygems.org'

gem 'app'
gem 'builder'
gem 'capistrano'
gem 'capistrano-ext'
gem 'capistrano-php'
gem 'capistrano-spec'
gem 'foreman'
gem 'guard'
gem 'guard-bundler'
gem 'guard-compass'
gem 'guard-sprockets'
gem 'rake'
gem 'rb-inotify'
gem 'w3c_validators'
