namespace :app do

  desc "Create MODx configuration"
  task :setup do
    modx_config = ERB.new <<-EOF
<?php

/* THIS FILE IS AUTOGENERATED - DO NOT EDIT!

  DateTime: #{Time.now}

*/
?>
EOF
    put modx_config.result, "#{shared_path}/modx-config.php"
    run "rm -rf #{appdir}"
  end

  desc "Make configuration symlink"
  task :symlink do
  end

  desc "Set permissions"
  task :permissions do
  end

end

namespace :cache do

  desc 'Create directories'
  task :setup do 
  end

  desc 'Symlink directories'
  task :symlink do
  end

end

namespace :db do
  desc "Change configuration stored in DB"
  task :config do
  end
end
