namespace :app do

  desc "Create MODx configuration"
  task :setup do
    modx_config = ERB.new <<-EOF
<?php

/* THIS FILE IS AUTOGENERATED - DO NOT EDIT!

  DateTime: #{Time.now}

*/
/* define the MODX path constants necessary for core installation */
define('MODX_CORE_PATH', dirname(dirname(__FILE__)) . '/core/');
define('MODX_CONFIG_KEY', 'config');

/* define the connection variables */
define('XPDO_DSN', 'mysql:host=#{db_host};dbname=#{db_name};charset=utf8');
define('XPDO_DB_USER', '#{db_user}');
define('XPDO_DB_PASS', '#{db_pass}');
define('XPDO_TABLE_PREFIX', '#{db_prefix}');
?>
EOF
    put modx_config.result, "#{shared_path}/build.config.php"
    run "rm -rf #{appdir}"
  end

  desc "Make configuration symlink"
  task :symlink do
  end

  desc "Set permissions"
  task :permissions do
  end

end

namespace :cache do

  desc 'Create directories'
  task :setup do 
  end

  desc 'Symlink directories'
  task :symlink do
  end

end

namespace :db do
  desc "Change configuration stored in DB"
  task :config do
  end
end
